baseUrl: "https://ustitc.me"
enableRobotsTXT: true

params:
  email: "ruslan@ustitc.me"
  description: ""
  dateFormat: "2006-01-02"
  paginationSinglePost: false
  readMore: false
  disableSummary: true
  toc: false
  tocWordCount: 300
  social:
    - id: github
      name: ustitc

defaultContentLanguage: "en"
languages:
  en:
    languageName: "English"
    title: "Ruslan Ustitc"
    params:
      author: "Ruslan Ustitc"
    menu:
      main:
        - name: Blog
          identifier: blog
          url: /blog/
          weight: 1

markup:
  highlight:
    noClasses: false
