baseUrl: "https://ustitc.me"
enableRobotsTXT: true

params:
  email: "ruslan@ustitc.me"
  author: "Ruslan Ustitc"
  description: ""
  dateFormat: "2006-01-02"

title: "Ruslan Ustitc"

markup:
  goldmark:
    renderHooks:
      link:
        enableDefault: true
  highlight:
    noClasses: false

menu:
  main:
    - name: Blog
      identifier: blog
      url: /blog/
      weight: 1
