baseUrl: "https://blog.ustits.dev"
theme: "anubis"
paginate: 5
enableRobotsTXT: true

params:
  email: "ustitsruslan@gmail.com"
  description: ""
  dateFormat: "2006-01-02"
  paginationSinglePost: false
  style: light
  readMore: false
  disableSummary: true
  toc: false
  tocWordCount: 300
  copyCodeButton: true
  rssAsSocialIcon: false
  mathjax: false
  utterancesRepo: ""
  utterancesTheme: ""
  utterancesIssue: ""
  utterancesLabel: ""
  graphcommentId: ""
  isso:
    enabled: false
  UmamiAnalytics:
    enabled: false
  social:
    - id: github
      name: ustitc
    - id: twitter
      name: ustitc
    - id: telegram
      name: ustitc
    - id: linkedin
      name: ustitc
    - id: goodreads
      url: 'https://www.goodreads.com/ustitc'

defaultContentLanguage: "en"
languages:
  ru:
    languageName: "Русский"
    title: "DevБлог Устица"
    params:
      author: "Руслан Устиц"
    menu:
      main:
        - name: Статьи
          identifier: posts
          url: /
          weight: 1
        - name: Проекты
          identifier: projects
          url: /projects/
          weight: 2
        - name: Обо мне
          identifier: about
          url: /about/
          weight: 3
        - name: CV
          identifier: cv
          url: /cv/ruslan_ustitc_cv.pdf
          weight: 4
  en:
    languageName: "English"
    title: "Ustitc's DevBlog"
    params:
      author: "Ruslan Ustitc"
    menu:
      main:
        - name: Articles
          identifier: posts
          url: /
          weight: 1
        - name: Projects
          identifier: projects
          url: /projects/
          weight: 2
        - name: About me
          identifier: about
          url: /about/
          weight: 3
        - name: CV
          identifier: cv
          url: /cv/ruslan_ustitc_cv.pdf
          weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true
