baseUrl = "https://blog.ustits.dev"
languageCode = "ru"
defaultContentLanguage = "ru"
title = "DevБлог Устица"
theme = "anubis"
paginate = 5
enableRobotsTXT = true

[params]
author = "Руслан Устиц"
email = "ustitsruslan@gmail.com"
description = ""
dateFormat = "2006-01-02"
paginationSinglePost = false
style = "light"
readMore = false
disableSummary = true
# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "github"
name = "ustits"

[[params.social]]
id = "twitter"
name = "r_ustits"

[[params.social]]
id = "telegram"
name = "ustits"

[languages.ru]
languageName = "Русский"

[[menu.main]]
name = "Статьи"
identifier = "posts"
url = "/"
weight = 1

[[menu.main]]
name = "Проекты"
identifier = "projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Обо мне"
identifier = "about"
url = "/about/"
weight = 3

[languages.en]
languageName = "English"
title = "Ustits's DevBlog"
author = "Ruslan Ustits"

[[languages.en.menu.main]]
name = "Articles"
identifier = "posts"
url = "/"
weight = 1

[[languages.en.menu.main]]
name = "Projects"
identifier = "projects"
url = "/projects/"
weight = 2

[[languages.en.menu.main]]
name = "About me"
identifier = "about"
url = "/about/"
weight = 3

[[languages.en.params]]
locale = "en-us"

[markup.goldmark.renderer]
unsafe = true