baseUrl: "https://ustitc.me"
enableRobotsTXT: true
disableKinds: ["RSS"]

params:
  dateFormat: "2006-01-02"

title: "Ruslan Ustitc"

markup:
  goldmark:
    renderHooks:
      link:
        enableDefault: true
  highlight:
    noClasses: false

menu:
  main:
    - name: Blog
      identifier: blog
      url: /blog/
      weight: 1
    - name: Contact
      identifier: contact
      url: "mailto:ruslan@ustitc.me"
      weight: 2
