baseUrl: "https://ustitc.me"
enableRobotsTXT: true

params:
  email: "ruslan@ustitc.me"
  author: "Ruslan Ustitc"
  description: ""
  dateFormat: "2006-01-02"
  social:
    - id: github
      name: ustitc

title: "Ruslan Ustitc"

markup:
  highlight:
    noClasses: false

menu:
  main:
    - name: Blog
      identifier: blog
      url: /blog/
      weight: 1
